package GUI;

import Napakalaki.Monster;

public class MonsterView extends javax.swing.JPanel {

    /**
     * Creates new form MonsterView
     */
    public MonsterView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        nameLabel = new javax.swing.JLabel();
        levelLabel = new javax.swing.JLabel();
        levelProgressBar = new javax.swing.JProgressBar();
        prizeView = new GUI.PrizeView();
        badConsequenceView = new GUI.BadConsequenceView();
        levelTextField = new javax.swing.JTextField();
        prizeTextField = new javax.swing.JTextField();
        levelVsCultistLabel = new javax.swing.JLabel();
        levelCultistTextField = new javax.swing.JTextField();
        monsterImageView = new javax.swing.JLabel();

        nameLabel.setFont(new java.awt.Font("Droid Sans", 1, 12)); // NOI18N
        nameLabel.setText("¿¿??");

        levelLabel.setText("Combat Level:");

        levelProgressBar.setMaximum(21);
        levelProgressBar.setToolTipText("");

        badConsequenceView.setBorder(javax.swing.BorderFactory.createTitledBorder("Bad Consequence"));

        levelTextField.setEditable(false);
        levelTextField.setFont(new java.awt.Font("Open Sans", 0, 10)); // NOI18N
        levelTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        levelTextField.setText("?");

        prizeTextField.setEditable(false);
        prizeTextField.setFont(new java.awt.Font("Open Sans", 0, 10)); // NOI18N
        prizeTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        prizeTextField.setText("? tesoros, ? niveles.");

        levelVsCultistLabel.setText("Level vs cultist:");

        levelCultistTextField.setEditable(false);
        levelCultistTextField.setFont(new java.awt.Font("Open Sans", 0, 10)); // NOI18N
        levelCultistTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        levelCultistTextField.setText("?");

        monsterImageView.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/No_Monster.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addComponent(prizeView, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(prizeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(badConsequenceView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nameLabel)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(levelVsCultistLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(levelCultistTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(levelLabel)
                                        .addGap(29, 29, 29)
                                        .addComponent(levelTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addComponent(levelProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 138, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(monsterImageView, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(nameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(levelLabel)
                            .addComponent(levelTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(levelProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(levelVsCultistLabel)
                    .addComponent(levelCultistTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(prizeView, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(prizeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(monsterImageView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(badConsequenceView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private GUI.BadConsequenceView badConsequenceView;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField levelCultistTextField;
    private javax.swing.JLabel levelLabel;
    private javax.swing.JProgressBar levelProgressBar;
    private javax.swing.JTextField levelTextField;
    private javax.swing.JLabel levelVsCultistLabel;
    private javax.swing.JLabel monsterImageView;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField prizeTextField;
    private GUI.PrizeView prizeView;
    // End of variables declaration//GEN-END:variables

  Monster monsterModel;

    
  public void setMonster( Monster m ) {
    monsterModel = m;
       
    nameLabel.setText( m.getName() );
    levelTextField.setText( String.valueOf( m.getCombatLevel() ) );
    levelCultistTextField.setText( String.valueOf( m.getCombatLevelAgainstCultistPlayer() ) );
    levelProgressBar.setValue( m.getCombatLevel() );
    prizeTextField.setText( m.getPrize().toString() );
    badConsequenceView.setBadConsequence( m.getBadConsequence() );
	String name = m.getName();
	monsterImageView.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/" + name + ".png")));	
        
    repaint();
    revalidate();
  }
	public void setHiddenMonster( ) {
    nameLabel.setText( "¿¿??" );
    levelTextField.setText( "?" );
    levelCultistTextField.setText( "?" );
    levelProgressBar.setValue( 0 );
    prizeTextField.setText( "? tesoros, ? niveles." );
    badConsequenceView.setHiddenBadConsequence();
	monsterImageView.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/No_Monster.png")));
	
    repaint();
    revalidate();
	}
}
