/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;
import Napakalaki.Treasure;

/**
 *
 * @author less
 */
public class TreasureView extends javax.swing.JPanel {

    /**
     * Creates new form TreasureView
     */
    public TreasureView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NameLabel = new javax.swing.JLabel();
        typeLabel = new javax.swing.JLabel();
        bonusLabel = new javax.swing.JLabel();

        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        NameLabel.setForeground(new java.awt.Color(0, 0, 0));
        NameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NameLabel.setText("Tesoro");

        typeLabel.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        typeLabel.setText("TIPO");

        bonusLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bonusLabel.setText("bonus");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(typeLabel)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(NameLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
            .addComponent(bonusLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(typeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bonusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getAccessibleContext().setAccessibleName("");
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
       if ( selected ) {
           setBackground(new java.awt.Color(134, 134, 134));
           selected = false;
       }
       else {
           setBackground(new java.awt.Color(222, 222, 222));
           selected = true;
       }
       repaint();
    }//GEN-LAST:event_formMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel NameLabel;
    private javax.swing.JLabel bonusLabel;
    private javax.swing.JLabel typeLabel;
    // End of variables declaration//GEN-END:variables

    Treasure treasureModel;
    boolean selected = false;
    
    public void setTreasure( Treasure t ) {
        if ( t != null )
        {
            treasureModel = t;

            NameLabel.setText( t.getName() );

            String bonus = "+";
            String type = "";
            bonus += t.getBonus();

            bonusLabel.setText( bonus );

            if ( null != t.getType() )
            {
                switch (t.getType()) 
                {
                case ARMOR:
                    type = "ARMOR";     break;
                case BOTHHANDS:
                    type = "BOTHHANDS"; break;
                case HELMET:
                    type = "HELMET";    break;
                case ONEHAND:
                    type = "ONEHAND";   break;
                case SHOES:
                    type = "SHOES";     break;
                case JOKER:
                    type = "JOKER";     break;
                default:
                    break;
                }
            }

            typeLabel.setText( type );
            repaint();
            revalidate();
        }
    }
    
    public Boolean isSelected() {
        return selected;
    }
    
    public Treasure getTreasure() {
        return treasureModel;
    }
}
